### ISSUE TITLE
Discrepancy between airtap README and .airtap.yml structure which uses this library

### ISSUE THREAD

**Issue by jzombie** [airtap/the-last-browser-launcher#3]
In regards to reverted PR: https://github.com/airtap/airtap/pull/314 (see attached screenshots there).

There appears to be some discrepancy between the way launch args are passed to browsers, vs. what is listed in the README documentation on airtap.

The README says to pass options.launch.args (https://github.com/airtap/airtap/blob/master/README.md),  while this library expects options.args https://github.com/airtap/the-last-browser-launcher/blob/8049d3ac7108b741a3770cb76f56dc1dba2aae9d/lib/launch/index.js#L146

This screenshot might be helpful to illustrate:

![args](https://user-images.githubusercontent.com/1139657/117469740-10c59600-af24-11eb-962f-17a414efa01b.png)

**Comment by vweevers** [comment]
https://github.com/airtap/airtap/pull/314#issuecomment-834516873

**Comment by jzombie** [comment]
Well, I stand corrected.  The documentation I referred to was apparently airtap-playwright.

It is slightly confusing that the options are structured a bit different, but I assume it would be more of an impact to change it than leave it alone at this point.
